name: "Deployment"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deployment:
    name: 🚀 GCP Deploy
    runs-on: ubuntu-latest

    steps:
      # This step creates a new deployment, check them out here:
      # https://github.com/Khenziii/croissantdealer/deployments
      - name: Start Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.TOKEN_GITHUB }}
          env: Production

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: khenzii
          password: ${{ secrets.DOCKER_PAT }}

      - name: [Default] Docker Build & Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: khenzii/croissantdealer:latest

      - name: [Web Server] Docker Build & Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: khenzii/croissantdealer:web-server-latest
          build-args: WEB_SERVER=true

      - name: Trigger Deployment Webhook
        run: |
          curl -X POST -d {} "${{ secrets.DEPLOY_WEBHOOK_URL }}" -H "Content-Type: application/json"

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.TOKEN_GITHUB }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
